# Generated by Django 6.0.7 on 2026-08-03 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Programming", "Programming"),
                            ("Design", "Design"),
                            ("Languages", "Languages"),
                            ("Music", "Music"),
                            ("Academics", "Academics"),
                            ("Business", "Business"),
                            ("Other", "Other"),
                        ],
                        default="Programming",
                        max_length=50,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[("TEACH", "Teach"), ("LEARN", "Learn")],
                        default="TEACH",
                        max_length=10,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Intermediate",
                        max_length=20,
                    ),
                ),
                ("rating", models.FloatField(default=5.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(blank=True, default="", max_length=150)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("credits", models.IntegerField(default=10)),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
