# Generated by Django 6.0.7 on 2026-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_skill_userprofile_delete_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
