# Generated by Django 6.1 on 2026-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_add_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_hours',
            field=models.CharField(blank=True, default='10 hrs / week', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('c1.jpg', 'C1'), ('c2.jpg', 'C2'), ('c3.jpg', 'C3'), ('c4.jpg', 'C4'), ('c5.jpg', 'C5'), ('c6.jpg', 'C6'), ('w1.jpg', 'W1'), ('w2.jpg', 'W2')], default='c1.jpg', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learn_skills',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schedule',
            field=models.CharField(blank=True, default='Weekdays after class', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_hours',
            field=models.BooleanField(default=True),
        ),
    ]
