# Generated by Django 6.1 on 2026-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_userprofile_average_rating_userprofile_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
