# Generated by Django 6.1 on 2026-10-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_session_ai_summary_session_summary_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='room_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='session_audio/')),
                ('transcript', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('consent_learner', models.BooleanField(default=False)),
                ('consent_teacher', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='editor.session')),
            ],
        ),
    ]
